# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_match"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "Basic Regular Expressions"
categories = ["Regular Expressions"]
keywords = ["fortran", "BRE", "RE", "regular expressions"]
homepage = "https://github.com/urbanjost/M_match.git"

[[executable]]
name="seek"
source-dir="app"
main="seek.f90"

[[test]]
name="test_suite_M_match"
source-dir="test"
main="test_suite_M_match.f90"
